[tool.ruff]
target-version = "py39"
src = ["src"]
select = ["ALL"]
line-length = 120
ignore = [
    "A002",
    "D",
    "EM101",
    "I",
    "PTH123",
    "TRY003",
    "RET504",
    "S113",
    "S311",
    "UP007",
    "C901",
    "PTH109",
    "PERF402",
    "ANN101",
    "PLR0915",
]

[tool.ruff.per-file-ignores]
"__init__.py" = [
    "D104",
    "F401",
]
"main.py" = [
    "N801",
    "PLR0912",
    "PLW2901",
]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
